[[news]]
date = "2026.03"
content = "🎉 One paper has been accepted at **IEEE TBD**, congratulations to **Shuxin Chen**!"

[[news]]
date = "2025.12"
content = "🎉 Awarded the **Doctoral Student Program of the Young S&T Talents Cultivation Project, CAST** (National-Level)"

[[news]]
date = "2025.10"
content = "Awarded the First Grade Academic Scholarship of Hangzhou Dianzi University"

[[news]]
date = "2025.09"
content = "🎉 One paper has been accepted at **IJCAI 2025**."

[[news]]
date = "2025.05"
content = "🎉 Awarded the **CSC Scholarship for Joint PhD at the University of Sydney**"

[[news]]
date = "2024.09"
content = "Started PhD at the School of Cyberspace, Hangzhou Dianzi University"

[[news]]
date = "2024.05"
content = "Awarded Outstanding Graduate at both the Zhejiang Provincial and University level"

[[news]]
date = "2023.11"
content = "🎉 Awarded the **National Scholarship for Master's Students**"
